.TH "ILT" 1 "Image Layout Toolkit v1.0" "Montreal Neuro. Inst."
.SH NAME
ILT - Image Layout Toolkit - Perl5 library for generating arrays of images of
volumes and geometry
.SH DESCRIPTION
.I ILT
is an object-oriented Perl5 library which provides methods to create arrays
of images of MINC volume slices and geometry.  Documentation currently exists
of a tutorial, which you can access from netscape
.I
netscape /usr/local/mni/doc/ILT/ILT_tutorial.html
. Example files for this tutorial are in
.I
/usr/local/mni/doc/ILT/ILT_tutorial_example_code
and the sample output produced by these examples are in
.I
/usr/local/mni/doc/ILT/ILT_tutorial_example_output
.

.SH AUTHOR
David MacDonald
.SH BUGS
ILT is currently usable for most tasks, but some features are not fully
implemented, and certainly, there may be bugs.
.SH BUG REPORTS TO
David MacDonald	      david@bic.mni.mcgill.ca
.SH COPYRIGHTS
.ps 18
\fB\(co\fR\s12 Copyright 1998 by David MacDonald and McConnell Brain Imaging Centre
